"""The devices table: one row per CLI, phone or browser session."""

# The owner writes the Device class here (build-plan stage 1). What the table
# must allow, from shared/docs/product/domains/accounts.md, decisions #24,
# #25 and #29, and the development rules:
#
# - id: a UUID generated by the application.
# - user_id: the owner column (rules, 10), a foreign key to users.id.
# - user: the relationship to User; the tests create Device(user=...).
# - name: shown in the device list.
# - token_hash: the token's SHA-256 (32 bytes), unique; the token itself is
#   never stored (criterion 4).
# - created_at (when it was paired) and last_used_at, both timestamptz:
#   the device list shows them, and 90 days without use expire a token (#25).
# - Revoking: delete the row, or keep it with a revoked_at time? Your choice;
#   revoked devices answer 401 and disappear from the list either way.
#
# The tests create Device(user=... or user_id=..., name=..., token_hash=...).
#
# User and Device live in separate files, so importing one from the other
# both ways would be circular. Refer to the other class by its name as a
# string, Mapped["User"], and import it only for the type checker:
#
#     from typing import TYPE_CHECKING
#     if TYPE_CHECKING:
#         from titan_server.domains.accounts.models.user import User
#
# https://docs.sqlalchemy.org/en/20/orm/basic_relationships.html
