"""The users table."""

# The owner writes the User class here (build-plan stage 1). What the table
# must allow, from shared/docs/product/domains/accounts.md and the
# development rules:
#
# - id: a UUID generated by the application, not the database (rules, 10).
# - username: unique; sign-in looks a user up by it.
# - password_hash: the Argon2id hash only, never the password (criterion 2).
# - created_at: timestamptz (rules, 10).
# - Which user is the owner: create-owner refuses when one exists (criterion 6).
#   A flag, a role, or "the first user"? Your choice.
#
# The tests create User(username=..., password_hash=...).
#
# Examples: SQLAlchemy 2.0 "Declarative mapping" with Mapped[...] and
# mapped_column(): https://docs.sqlalchemy.org/en/20/orm/quickstart.html
